#include "libhttp.h"
#include "util.h"

#define X(a) [a] = #a + 7

// Mapping of HTTP status codes to stringified names.
const char* http_status_names[] = {
    ENUM_NAME(CONTINUE),
    ENUM_NAME(SWITCHING_PROTOCOLS),
    ENUM_NAME(PROCESSING),
    ENUM_NAME(EARLY_HINTS),

    ENUM_NAME(OK),
    ENUM_NAME(CREATED),
    ENUM_NAME(ACCEPTED),
    ENUM_NAME(NON_AUTHORITATIVE_INFO),
    ENUM_NAME(NO_CONTENT),
    ENUM_NAME(RESET_CONTENT),
    ENUM_NAME(PARTIAL_CONTENT),
    ENUM_NAME(MULTISTATUS),
    ENUM_NAME(ALREADY_REPORTED),
    ENUM_NAME(IM_USED),

    ENUM_NAME(MULTIPLE_CHOICES),
    ENUM_NAME(MOVED_PERMANENTLY),
    ENUM_NAME(FOUND),
    ENUM_NAME(SEE_OTHER),
    ENUM_NAME(NOT_MODIFIED),
    ENUM_NAME(USE_PROXY),
    ENUM_NAME(NULL_),
    ENUM_NAME(TEMPORARY_REDIRECT),
    ENUM_NAME(PERMANENT_REDIRECT),

    ENUM_NAME(BAD_REQUEST),
    ENUM_NAME(UNAUTHORIZED),
    ENUM_NAME(PAYMENT_REQUIRED),
    ENUM_NAME(FORBIDDEN),
    ENUM_NAME(NOT_FOUND),
    ENUM_NAME(METHOD_NOT_ALLOWED),
    ENUM_NAME(NOT_ACCEPTABLE),
    ENUM_NAME(PROXY_AUTH_REQUIRED),
    ENUM_NAME(REQUEST_TIMEOUT),
    ENUM_NAME(CONFLICT),
    ENUM_NAME(GONE),
    ENUM_NAME(LENGTH_REQUIRED),
    ENUM_NAME(PRECONDITION_FAILED),
    ENUM_NAME(REQUEST_ENTITY_TOO_LARGE),
    ENUM_NAME(REQUEST_URI_TOO_LONG),
    ENUM_NAME(UNSUPPORTED_MEDIA_TYPE),
    ENUM_NAME(REQUESTED_RANGE_NOT_SATISFIABLE),
    ENUM_NAME(EXPECTATION_FAILED),
    ENUM_NAME(TEAPOT),
    ENUM_NAME(MISDIRECTED_REQUEST),
    ENUM_NAME(UNPROCESSABLE_ENTITY),
    ENUM_NAME(LOCKED),
    ENUM_NAME(FAILED_DEPENDENCY),
    ENUM_NAME(TOO_EARLY),
    ENUM_NAME(UPGRADE_REQUIRED),
    ENUM_NAME(PRECONDITION_REQUIRED),
    ENUM_NAME(TOO_MANY_REQUESTS),
    ENUM_NAME(REQUEST_HEADER_FIELDS_TOO_LARGE),
    ENUM_NAME(UNAVAILABLE_FOR_LEGAL_REASONS),

    ENUM_NAME(INTERNAL_SERVER_ERROR),
    ENUM_NAME(NOT_IMPLEMENTED),
    ENUM_NAME(BAD_GATEWAY),
    ENUM_NAME(SERVICE_UNAVAILABLE),
    ENUM_NAME(GATEWAY_TIMEOUT),
    ENUM_NAME(HTTP_VERSION_NOT_SUPPORTED),
    ENUM_NAME(VARIANT_ALSO_NEGOTIATES),
    ENUM_NAME(INSUFFICIENT_STORAGE),
    ENUM_NAME(LOOP_DETECTED),
    ENUM_NAME(NOT_EXTENDED),
    ENUM_NAME(NETWORK_AUTHENTICATION_REQUIRED),
};

// Mapping of HTTP method name enums to stringified names.
const char* http_method_names[] = {
    X(METHOD_GET),     X(METHOD_HEAD),    X(METHOD_POST),
    X(METHOD_PUT),     X(METHOD_PATCH),   X(METHOD_DELETE),
    X(METHOD_CONNECT), X(METHOD_OPTIONS), X(METHOD_TRACE)};
