#include "libhttp.h"
#include "util.h"

#define X(e) [e] = #e + 7

// Mapping of HTTP status codes to stringified names.
const char* http_status_names[] = {
    X(STATUS_CONTINUE),
    X(STATUS_SWITCHING_PROTOCOLS),
    X(STATUS_PROCESSING),
    X(STATUS_EARLY_HINTS),

    X(STATUS_OK),
    X(STATUS_CREATED),
    X(STATUS_ACCEPTED),
    X(STATUS_NON_AUTHORITATIVE_INFO),
    X(STATUS_NO_CONTENT),
    X(STATUS_RESET_CONTENT),
    X(STATUS_PARTIAL_CONTENT),
    X(STATUS_MULTISTATUS),
    X(STATUS_ALREADY_REPORTED),
    X(STATUS_IM_USED),

    X(STATUS_MULTIPLE_CHOICES),
    X(STATUS_MOVED_PERMANENTLY),
    X(STATUS_FOUND),
    X(STATUS_SEE_OTHER),
    X(STATUS_NOT_MODIFIED),
    X(STATUS_USE_PROXY),
    X(STATUS_NULL_),
    X(STATUS_TEMPORARY_REDIRECT),
    X(STATUS_PERMANENT_REDIRECT),

    X(STATUS_BAD_REQUEST),
    X(STATUS_UNAUTHORIZED),
    X(STATUS_PAYMENT_REQUIRED),
    X(STATUS_FORBIDDEN),
    X(STATUS_NOT_FOUND),
    X(STATUS_METHOD_NOT_ALLOWED),
    X(STATUS_NOT_ACCEPTABLE),
    X(STATUS_PROXY_AUTH_REQUIRED),
    X(STATUS_REQUEST_TIMEOUT),
    X(STATUS_CONFLICT),
    X(STATUS_GONE),
    X(STATUS_LENGTH_REQUIRED),
    X(STATUS_PRECONDITION_FAILED),
    X(STATUS_REQUEST_ENTITY_TOO_LARGE),
    X(STATUS_REQUEST_URI_TOO_LONG),
    X(STATUS_UNSUPPORTED_MEDIA_TYPE),
    X(STATUS_REQUESTED_RANGE_NOT_SATISFIABLE),
    X(STATUS_EXPECTATION_FAILED),
    X(STATUS_TEAPOT),
    X(STATUS_MISDIRECTED_REQUEST),
    X(STATUS_UNPROCESSABLE_ENTITY),
    X(STATUS_LOCKED),
    X(STATUS_FAILED_DEPENDENCY),
    X(STATUS_TOO_EARLY),
    X(STATUS_UPGRADE_REQUIRED),
    X(STATUS_PRECONDITION_REQUIRED),
    X(STATUS_TOO_MANY_REQUESTS),
    X(STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE),
    X(STATUS_UNAVAILABLE_FOR_LEGAL_REASONS),

    X(STATUS_INTERNAL_SERVER_ERROR),
    X(STATUS_NOT_IMPLEMENTED),
    X(STATUS_BAD_GATEWAY),
    X(STATUS_SERVICE_UNAVAILABLE),
    X(STATUS_GATEWAY_TIMEOUT),
    X(STATUS_HTTP_VERSION_NOT_SUPPORTED),
    X(STATUS_VARIANT_ALSO_NEGOTIATES),
    X(STATUS_INSUFFICIENT_STORAGE),
    X(STATUS_LOOP_DETECTED),
    X(STATUS_NOT_EXTENDED),
    X(STATUS_NETWORK_AUTHENTICATION_REQUIRED),
};

// Mapping of HTTP method name enums to stringified names.
const char* http_method_names[] = {
    X(METHOD_GET),     X(METHOD_HEAD),    X(METHOD_POST),
    X(METHOD_PUT),     X(METHOD_PATCH),   X(METHOD_DELETE),
    X(METHOD_CONNECT), X(METHOD_OPTIONS), X(METHOD_TRACE)};
